name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.4.0)'
        required: true
        type: string
      create_tag:
        description: '是否自动创建 Git 标签'
        required: true
        type: boolean
        default: true
      prerelease:
        description: '是否为预发布版本'
        required: true
        type: boolean
        default: false

# 声明工作流所需权限
permissions:
  contents: write  # 允许创建 Release 和上传资产

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ inputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录和标签

      - name: Validate version format
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "错误: 版本号格式不正确，应为 x.y.z 格式"
            exit 1
          fi

      - name: Delete existing tag and release if exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v${{ inputs.version }}"

          # 检查并删除远程标签
          if git ls-remote --tags origin | grep -q "refs/tags/${TAG_NAME}$"; then
            echo "删除远程标签: ${TAG_NAME}"
            git push --delete origin ${TAG_NAME} || true
          fi

          # 检查并删除本地标签
          if git tag -l | grep -q "^${TAG_NAME}$"; then
            echo "删除本地标签: ${TAG_NAME}"
            git tag -d ${TAG_NAME} || true
          fi

          # 检查并删除已存在的 Release
          RELEASE_ID=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${TAG_NAME}" \
            | jq -r '.id // empty')

          if [ -n "$RELEASE_ID" ]; then
            echo "删除已存在的 Release: ${TAG_NAME} (ID: ${RELEASE_ID})"
            curl -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}"
          fi

          echo "清理完成"

      - name: Create Git Tag
        if: ${{ inputs.create_tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ inputs.version }}" -m "Release v${{ inputs.version }}"
          git push origin "v${{ inputs.version }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ inputs.version }}
          release_name: Release v${{ inputs.version }}
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: ${{ inputs.prerelease }}

  build-gui:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            bundles: nsis,wix
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            bundles: deb,appimage
          - platform: macos-latest
            target: x86_64-apple-darwin
            bundles: dmg

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install WiX (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe" -OutFile "$env:TEMP\wix314.exe"
          Start-Process -FilePath "$env:TEMP\wix314.exe" -ArgumentList "/install", "/quiet", "/norestart" -Wait
          echo "WIX=$env:ProgramFiles (x86)\WiX Toolset v3.14" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: src-tauri/target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run build

      - name: List build artifacts (Debug)
        run: |
          echo "=== Listing bundle directory ==="
          ls -R src-tauri/target/release/bundle/ || echo "Bundle directory not found"

      - name: Upload Release Assets (Windows - NSIS)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/nsis/claude-code-config-manager_${{ needs.create-release.outputs.version }}_x64-setup.exe
          asset_name: claude-code-config-manager_${{ needs.create-release.outputs.version }}_x64-setup.exe
          asset_content_type: application/x-msdownload

      - name: Upload Release Assets (Windows - MSI zh-CN)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/msi/claude-code-config-manager_${{ needs.create-release.outputs.version }}_x64_zh-CN.msi
          asset_name: claude-code-config-manager_${{ needs.create-release.outputs.version }}_x64_zh-CN.msi
          asset_content_type: application/x-msi

      - name: Upload Release Assets (Windows - MSI en-US)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/msi/claude-code-config-manager_${{ needs.create-release.outputs.version }}_x64_en-US.msi
          asset_name: claude-code-config-manager_${{ needs.create-release.outputs.version }}_x64_en-US.msi
          asset_content_type: application/x-msi

      - name: Upload Release Assets (Linux - DEB)
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/deb/claude-code-config-manager_${{ needs.create-release.outputs.version }}_amd64.deb
          asset_name: claude-code-config-manager_${{ needs.create-release.outputs.version }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Release Assets (Linux - AppImage)
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/appimage/claude-code-config-manager_${{ needs.create-release.outputs.version }}_amd64.AppImage
          asset_name: claude-code-config-manager_${{ needs.create-release.outputs.version }}_amd64.AppImage
          asset_content_type: application/x-executable

      - name: Upload Release Assets (macOS - DMG)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/dmg/claude-code-config-manager_${{ needs.create-release.outputs.version }}_x64.dmg
          asset_name: claude-code-config-manager_${{ needs.create-release.outputs.version }}_x64.dmg
          asset_content_type: application/x-apple-diskimage

  build-cli:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: claude-config.exe
            archive: claude-config-cli-$VERSION-Windows-x86_64.zip
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            binary: claude-config
            archive: claude-config-cli-$VERSION-Linux-x86_64.tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: claude-config
            archive: claude-config-cli-$VERSION-Darwin-x86_64.tar.gz

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cli-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cli-cargo-

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: claude-config-cli/target
          key: ${{ runner.os }}-cli-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cli-cargo-build-

      - name: Build CLI
        working-directory: claude-config-cli
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          $version = "${{ needs.create-release.outputs.version }}"
          $archive = "${{ matrix.archive }}".Replace('$VERSION', $version)
          Copy-Item "claude-config-cli/target/${{ matrix.target }}/release/${{ matrix.binary }}" -Destination "claude-config.exe"
          Compress-Archive -Path "claude-config.exe" -DestinationPath $archive
          echo "ARCHIVE_NAME=$archive" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Package (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          version="${{ needs.create-release.outputs.version }}"
          archive="${{ matrix.archive }}"
          archive="${archive/\$VERSION/$version}"
          cp "claude-config-cli/target/${{ matrix.target }}/release/${{ matrix.binary }}" claude-config
          tar czf "$archive" claude-config
          echo "ARCHIVE_NAME=$archive" >> $GITHUB_ENV

      - name: Upload CLI Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          asset_content_type: application/octet-stream
